"
I store metadata for this package. These meta data are used by other tools such as the SmalllintManifestChecker and the critics Browser
"
Class {
	#name : #ManifestPhxPjVue,
	#superclass : #PackageManifest,
	#category : #'Phx-Pj-Vue-Manifest'
}

{ #category : #'code-critics' }
ManifestPhxPjVue class >> ruleRBSentNotImplementedRuleV1FalsePositive [
	^ #(#(#(#RGPackageDefinition #(#'Phx-Pj-Vue')) #'2020-09-13T20:06:16.757065+02:00') )
]
